qtools: update tools to use a configuration file to specify the upstream  tree
Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>

diff --git a/ufcompare b/ufcompare
--- a/ufcompare
+++ b/ufcompare
@@ -3,7 +3,12 @@
 # description
 . libparsemail.sh
 
-UPSTREAM=~/kernel/linus-2.6/
+CONFIG=$HOME/.config/qtools/config.sh
+if [ ! -f $CONFIG ]; then
+	echo "Unable to find the configuration file. Please create one at $CONFIG with UPSTREAM=<path to Linus' tree>" >&2;
+	exit 1;
+fi
+. $CONFIG;
 
 if [ -z "$1" ]; then
 	echo "$0 <file>" >&2;
diff --git a/umatch b/umatch
--- a/umatch
+++ b/umatch
@@ -1,7 +1,12 @@
 #!/bin/bash
 . libparsemail.sh
 
-UPSTREAM=~/kernel/linus-2.6/
+CONFIG=$HOME/.config/qtools/config.sh
+if [ ! -f $CONFIG ]; then
+	echo "Unable to find the configuration file. Please create one at $CONFIG with UPSTREAM=<path to Linus' tree>" >&2;
+	exit 1;
+fi
+. $CONFIG;
 
 tmp=$(mktemp);
 
