ufcompare: try harder to find a commit id
Signed-off-by: Aristeu Rozanski <arozansk@redhat.com>

diff --git a/ufcompare b/ufcompare
--- a/ufcompare
+++ b/ufcompare
@@ -11,15 +11,18 @@ fi
 . $CONFIG;
 
 if [ -z "$1" ]; then
-	echo "$0 <file>" >&2;
+	echo "$0 <file> [sha]" >&2;
 	exit 1;
 fi
 file=$1;
+commit=$2;
 
-commit=$(get_git_references patches/$(quilt top) | head -n 1);
 if [ -z "$commit" ]; then
-	echo "couldn't find a commit id on the patch's description" >&2;
-	exit 1;
+	commit=$(get_git_references patches/$(quilt top) | head -n 1);
+	if [ -z "$commit" ]; then
+		echo "couldn't find a commit id on the patch's description" >&2;
+		exit 1;
+	fi
 fi
 
 tmp=$(mktemp);
